### ISSUE TITLE
Cannot authenticate when testing locally using `yarn develop`

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/learn#105]
When developing and testing local, if you click the login button it takes you to https://auth.freecodecamp.org which then redirects you to https://beta.freecodecamp.org/ when you enter the authorization code that is emailed to you. How can we authenticate locally when testing?

**Comment by Bouncey** [comment]
@raisedadead is working towards a solution for local auth.

**Comment by tchaffee** [comment]
@raisedadead Is there anything I can do to help with this and move things along?

**Comment by nathanhannig** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/17382
