### ISSUE TITLE
Map is not showing completed challenges

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/learn#115]
I can sign in using the legacy github method and get the following screen, so I'm sure signin was successful:

![selection_104](https://user-images.githubusercontent.com/148813/40744751-eaf834be-642b-11e8-8b78-1eac8790539c.png)

When I click the button to "Go to my next coding challenge", it still shows the login button:

![selection_105](https://user-images.githubusercontent.com/148813/40744834-2c634718-642c-11e8-8670-c123575411d5.png)

Then when I complete a couple of challenges, it does not show those challenges as completed in the map.

![selection_106](https://user-images.githubusercontent.com/148813/40744876-477ba3d8-642c-11e8-9279-5ff7d789beb5.png)

When I try to login in again by pressing the login button, it shows me as still logged in.

I don't think this is a problem with the recent changes I made to the map because when I look at the React debug tab in Chrome and look at the challenges, none of them have the `isCompleted` property.

**Comment by akkatracker** [comment]
A lot fo people have an issue with the logins not carrying across (myself included), if you wait a bit I've found that sometimes it'll log you in and then the map will populate.

**Comment by Bouncey** [comment]
@tchaffee we have rolled out a few changes since your screenshots were taken. Can you please try again and let us know if this is resolved.

**Comment by tchaffee** [comment]
@Bouncey It's still a problem. Aside from the layout differences, the only difference I noted is that the "Sign In" button on learn.freecodecamp.org looks like it is loading for a minute. But then it still shows "Sign In". It seems like it's not detecting I'm signed in. When I click on the "Sign In" button, I get a page that says "Welcome Todd Chaffee", showing I'm already signed in. I'm available all day to help out with this if you need anything else.

**Comment by akkatracker** [comment]
I just wanted to confirm, that the login feature seems to be working pretty much flawlessly, so it's now just @tchaffee 's issue

**Comment by tchaffee** [comment]
I just tested again and I still have the same problem. Both with the login weirdness and the map not updating.

**Comment by Bouncey** [comment]
@tchaffee are you able to join on a google hangouts with me and we can talk about this.

**Comment by tchaffee** [comment]
@Bouncey I'm on a business trip for the next week. I can try to find some time and let you know but I can't guarantee it.

**Comment by Bouncey** [comment]
@raisedadead could this be related to the stale cookie thing we found yesterday?

**Comment by tchaffee** [comment]
@Bouncey can you try to give me some times that are good for you and I can try to find some time in the next few days?

**Comment by raisedadead** [comment]
Possibly related freeCodeCamp/freeCodeCamp#17565

**Comment by tchaffee** [comment]
@Bouncey I'm ready to look at this when you are available. Any time from 10am until about 9pm São Paulo, Brazil time is good for me, but if you can give me some times of when you'll be available I can make sure I'm here. I think you already have my Google Hangout contact info?

**Comment by Bouncey** [comment]
@tchaffee 10am your time works for me. I will send an invite to your registered email address in the morning. @raisedadead would you be available?

**Comment by tchaffee** [comment]
@Bouncey @raisedadead just to follow up on our call and get this documented - clearing cookies solved the problem. It was likely an outdated JWT token that the main domain was recognizing but the learn domain wasn't accepting.

I think we left this at @raisedadead doing some more research on how cookies work between the various domains before we do anything else?

**Comment by raisedadead** [comment]
Closing in favor of freeCodeCamp/freeCodeCamp#17565
