### ISSUE TITLE
"Applied Visual Design - Create a More Complex Shape Using CSS and HTML" does not use CSS3 pseudo-element selector syntax

### ISSUE THREAD

**Issue by SuperGeniusZeb** [freeCodeCamp/learn#121]
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-more-complex-shape-using-css-and-html

This lesson currently uses the old CSS2 pseudo-element syntax: `thing:pseudo-element`. It should be updated to use the CSS3 syntax: `thing::pseudo-element`.

See also:
https://developer.mozilla.org/en-US/docs/Web/CSS/pseudo-elements
https://drafts.csswg.org/selectors-3/#pseudo-elements

**Comment by Bouncey** [comment]
There is a difference between `:` and `::`.

`:` is for pseudo classes like `:hover` and `:focus`

`::` is for pseudo elements like `::before` and `::after`

In most cases [it doesn't really matter](https://www.smashingmagazine.com/2016/05/an-ultimate-guide-to-css-pseudo-classes-and-pseudo-elements/#single-or-double-colon-for-pseudo-elements)

I would be happy to see the changes made in freeCodeCamp/freeCodeCamp though :+1:

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/curriculum #14](https://github.com/freeCodeCamp/curriculum/issues/14) via [**ZenHub**](https://www.zenhub.com/)
