### ISSUE TITLE
"Applied Visual Design - Use the del Tag to Strikethrough Text" is using the wrong element semantically

### ISSUE THREAD

**Issue by SuperGeniusZeb** [freeCodeCamp/learn#123]
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-del-tag-to-strikethrough-text/

This lesson teaches that the `<del>` element represents "a section of text is no longer valid". However, according to the HTML spec, that is the purpose of the `<s>` element. The `<del>` element is supposed to be used to represent text that has been deleted from a document during an edit (similar to the `<ins>` element which represents content that has been added in by an edit).

See also:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s
https://www.w3.org/TR/html52/edits.html#the-del-element
https://www.w3.org/TR/html53/edits.html#the-del-element
https://www.w3.org/TR/html52/textlevel-semantics.html#the-s-element
https://www.w3.org/TR/html53/textlevel-semantics.html#the-s-element
https://html.spec.whatwg.org/multipage/edits.html#the-del-element
https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-s-element

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/curriculum #17](https://github.com/freeCodeCamp/curriculum/issues/17) via [**ZenHub**](https://www.zenhub.com/)
