### ISSUE TITLE
How about using Material Components?

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/learn#125]
Google recently unveiled big changes to Material Design, and they have great tools for creating a custom Material Design theme. Material Components is the framework that makes it easy to actually implement it in code.

Considering the regression in the UI many people complain about right now, I wondered if you ever considered using such a solution to create a unified design across all freeCodeCamp websites and products. 🙂

You can see all the docs, articles, confs and tools about Material Design on https://material.io

**Comment by Bouncey** [comment]
@thomaskuntzz Thanks for bringing this up. The styling is something we have talked about, but it's not a quick fix. The majority of the organisation is using bootstrap v3, the react apps are tied to bootstrap v3 through a component library we are using, `react-bootstrap`. `react-bootstrap` are working towards rolling out a v4 version of their library, but who knows how long that is going to take. 

We would love the have our own component library, both for react and traditional HTML/CSS, but big things are still going on like converting our back end into a graphql serverless infrastructure [OpenAPI](https://github.com/freecodecamp/open-api), an open source replacement for `meetup.com` and our own news website.

So yes, sorting out our UI components is on the road map, but we have many competing priorities when it comes to development hours.

**Comment by thomaskuntzz** [comment]
Okay, thanks for the answer! Is there any issue where the topic of a component library is being discussed?

**Comment by Jacob8765** [comment]
I use mdbreact [https://mdbootstrap.com/react/](url) in all my react projects and it works perfectly.

**Comment by tchaffee** [comment]
@Bouncey @QuincyLarson I'll offer again to create a roadmap so we can refer people to that in the README and we don't get open issues like this. It's kind of a big mystery to outsiders what the future plans are and I think it would help all contributors to understand what the near term vision is.

**Comment by thomaskuntzz** [comment]
@tchaffee Yep, a roadmap would definitely be worth it 👍
