### ISSUE TITLE
"CSS Flexbox - Align Elements Using the justify-content Property" should mention "space-evenly"

### ISSUE THREAD

**Issue by SuperGeniusZeb** [freeCodeCamp/learn#138]
https://learn.freecodecamp.org/responsive-web-design/css-flexbox/align-elements-using-the-justify-content-property

This lesson/challenge mentions most of the popular `justify-content` values except `space-evenly`. This one is very useful, and I think it should be mentioned, with a note that it is not properly supported in all major browsers (specifically Microsoft Edge and of course IE11) yet.

Note that if this is changed, the next lesson/challenge, "CSS Flexbox - Use the justify-content Property in the Tweet Embed", should also be changed to include `space-evenly` as a valid value:
https://learn.freecodecamp.org/responsive-web-design/css-flexbox/use-the-justify-content-property-in-the-tweet-embed/

See also:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15947692/
https://codepen.io/team/css-tricks/pen/zzJMGJ

**Comment by Bouncey** [comment]
`space-evenly` has poor support across the board [MDN Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Browser_compatibility).

I think there is a risk of confusing campers if they try it out in IE/Edge and it doesn't work as expected. I don't think this would be a required change right now.

**Comment by SuperGeniusZeb** [comment]
Okay, fair enough. Closing this issue.
