### ISSUE TITLE
Blank white screen after clicking curriculum

### ISSUE THREAD

**Issue by pcatana** [freeCodeCamp/learn#140]
Was doing some random exercise on learn.freecodecamp and wanted to check my curriculum. 
When I click on it, i get an empty screen. The only way to see the curriculum I have is to refresh the page once again. 

Device: Windows 10 April 2018 update
Browser: Chrome V. 66

![image](https://user-images.githubusercontent.com/19393057/40874986-346a38f6-6678-11e8-9603-575ac58fb484.png)
I get this issue right after me completing an exercise. I press CTRL + Enter and it directs me to the next exercise.
Then, I want to check the curriculum. As a result, i get the empty page. 
I've checked dev tools and it seems like the button doesn't have the ID to which is should direct itself?

![image](https://user-images.githubusercontent.com/19393057/40875520-ec82ba62-6678-11e8-8a8f-426fea61b1cb.png)

**Comment by tchaffee** [comment]
I can confirm I've seen this happen to me too. Occasional totally blank screen.

**Comment by Bouncey** [comment]
I think I have the steps to reproduce, at least in production.

1. Complete a challenge you haven't before
1. Run tests and pass
1. Submit and go to next challenge (modal button)
1. Click Curriculum in the nav bar

For some reason this doesn't happen with already completed challenges.
