### ISSUE TITLE
Remove the @freecodecamp/curriculum npm dependency

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/learn#146]
The @freecodecamp/curriculum npm dependency is at the wrong level and makes this package unnecessarily tied to that curriculum. It makes it difficult to use a different curriculum. A better approach would be to remove the dependency from this repo and leave this repo with just the curriculum neutral source code.

Another repo (freeCodeCamp/learnFreeCodeCamp?) could then pull both this repo and the @freecodecamp/curriculum dependencies in to combine the two.

**Comment by Bouncey** [comment]
I don't understand the benefit in that approach? 

Learn uses a custom plugin to pull challenges from the curriculum package. The learn platform was not designed to handle other types of curriculum packages?

**Comment by QuincyLarson** [comment]
@Bouncey I agree with @tchaffee's reasoning here. If someone hypothetically wanted to plug in their own curriculum, that should be an option. This said, I don't agree with the need for yet another repo, as @tchaffee is proposing. There must be a more graceful way.

Until we can come up with a better way, I think people forking Learn could just swap out the package with their own npm module. So barring a better approach, I propose we table this until we have finished updating the curriculum repo and have clear ways for campers to contribute to the curriculum.

**Comment by tchaffee** [comment]
Fine to close this for now. I'll take a closer look at this again when we have stabilized the contribution process and the repo structures.
