### ISSUE TITLE
Firefox: Page content hidden behind top navbar, Scroll issues

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#153]
@numoonchld commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17455)

#### Describe your problem and - if possible - how to reproduce it

When progressing to a new challenge after completing the current one, when the new page loads, the title of the challenge and some of the content at the top of the page gets hidden behind the green navbar. 

This is counter UI-flow as it prevents the user from the seeing the title of the new challenge after the challenge auto loads and everything. 

This doesn't happen when accessing a challenge directly from the curriculum, only when progressing through challenges using Ctrl+Enter.

#### Add a Link to the page with the problem

I'm noticing this in the Applied Visual Design section. 

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: macOS

#### If possible, add a screenshot here

![screen shot 2018-06-06 at 11 55 11 am](https://user-images.githubusercontent.com/17598505/41020452-8efa1b64-6980-11e8-9b9a-a0f03f672bad.png)

**Comment by ktajpuri** [comment]
Can I work on this one?

**Comment by ktajpuri** [comment]
I have noticed that in firefox, after doing ctrl + enter , when the new challenge is loading the panel scrolls up a bit, due to which the title gets hidden. Investigating what is making this happen in firefox. Same behaviour doesn't happen in chrome.

**Comment by ktajpuri** [comment]
@raisedadead  I tried to find the root cause but could not. Seems like some display:flux issue. If we make any flux related change in any of the components scrolling starts working. It can be any change!
I am having hard time with this one. I would suggest editing the title to more generic like, scroll issues with components in firefox.

**Comment by eng-sarah** [comment]
same here  
I can not scroll page to complete challenge   although ctrl+enter  complete challanege 

Tell us about your browser and operating system

    Browser Name: Firefox
    Browser Version: 60.0.2 (64-bit)
    Operating System: ubuntu 
on chrome it is working fine

**Comment by Jolt2bolt** [comment]
I realize when I use the zoom of firefox below 100% the page can seen completely. but the scroll bar nearly disapear. Maybe did the FFC page updated a component that have a bug related to firefox?

**Comment by ktajpuri** [comment]
@lallenfrancisl  I can confirm that both the issues are resolved now. Scrolling works fine and navigating challenge by ctrl + enter doesn't hide the top of challenge. Wondering what fixed it though.

**Comment by ktajpuri** [comment]
@raisedadead  I think this issue can be closed. Please have a look.
