### ISSUE TITLE
freecodecamp using googleapis CDN which is blocked in China

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#155]
@naibaben commented on [Tue Jun 05 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442)

#### Describe your problem and - if possible - how to reproduce it

Google Jquery is not accessible for China
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js

#### Tell us about your browser and operating system

* Browser Name: Google chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/39952042/40975542-e92b9118-68fd-11e8-843d-6e391f4ff7fe.png)

---

@QuincyLarson commented on [Tue Jun 05 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-394760280)

Thanks for the feedback. We could refactor this to use a different font. Can you still pass the challenge without getting the CDN link to work?

---

@MartinKolarik commented on [Tue Jun 05 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-394762919)

@QuincyLarson the issue is about jquery, not fonts.

---

@AbdulrahmanEng commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-394826646)

This article might help: https://weblogs.asp.net/jongalloway/using-cdn-hosted-jquery-with-a-local-fall-back-copy. @QuincyLarson.

---

@AbdulrahmanEng commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-394827595)

@naibaben, have you tried using the site through a VPN (virtual private network)?

---

@MartinKolarik commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-394829548)

I'd suggest using a China-friendly CDN like [jsDelivr](https://www.jsdelivr.com) instead. Using a local copy would be very slow for people in China and is unnecessary complicated.

---

@raisedadead commented on [Wed Jun 06 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17442#issuecomment-395044176)

We can alternatively bundle jQuery

**Comment by raisedadead** [comment]
We should switch to this for the jQuery CDN or alternatively bundle it.

```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
```

**Comment by Bouncey** [comment]
CDN please, not bundle. The bundle is big enough already
