### ISSUE TITLE
Open curriculum to current challenge

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#171]
@moT01 commented on [Tue Jun 12 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17557)

#### Describe your problem and - if possible - how to reproduce it
When you open the curriculum in a new session it opens like this...

<img width="494" alt="screen shot 2018-06-12 at 9 29 32 am" src="https://user-images.githubusercontent.com/20648924/41296785-4fb71ffe-6e23-11e8-8fe9-bee2b8e5cfef.png">

If you navigate to your current challenge and click on it, then go back to the curriculum (in the same session) - it will have the same section/sections open that you had open before but not scroll to where you were 

It would be nice if the curriculum/map navigated to your current challenge when you open it

**Comment by Nirajn2311** [comment]
You mean to say that it should automatically open the blocks of your current topic and scroll to your current challenge.

**Comment by im-ironclad** [comment]
@Nirajn2311 I believe that is what he means. When i made the PR for updating the styles on the curriculum map i noticed it was a bad UX for the map to always open the first tab as this issue states. I think it's worth refactoring the map to pull from the users last completed module if applicable.

**Comment by ktajpuri** [comment]
Working on this one.

**Comment by ktajpuri** [comment]
There are two issues here.
1. When you click on a challenge in the curriculum map, the API call to update currentChallengeId in database is made, but the fetch request is not made after success, so currentChallengeId in local state is not updated. 
2. Scrolling logic.
