### ISSUE TITLE
Indent sample code in lesson description

### ISSUE THREAD

**Issue by thefifthisa** [freeCodeCamp/learn#172]
#### Describe your problem and - if possible - how to reproduce it
Minor thing, but I think it would improve readability if the sample code below was properly indented like in other lesson descriptions.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/prevent-object-mutation

#### If possible, add a screenshot here
![es6_prevent object mutation](https://user-images.githubusercontent.com/30595954/41340428-e7531992-6f29-11e8-8311-a48756d151ab.png)

**Comment by Nirajn2311** [comment]
I’ll see what I can do about it.

**Comment by Nirajn2311** [comment]
There is a mistake in the code of FCC's curriculum node_module

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/curriculum #16](https://github.com/freeCodeCamp/curriculum/issues/16) via [**ZenHub**](https://www.zenhub.com/)
