### ISSUE TITLE
Clicking freeCodeCamp logo should always take you to www.freecodecamp.org

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/learn#177]
Even when on learn.freecodecamp.org, clicking the freeCodeCamp logo should take you to www.freecodecamp.org. 

![welcome_to_learn_freecodecamp_](https://user-images.githubusercontent.com/985197/41430335-50db2ade-6fd5-11e8-91b3-1f6b9cf70e60.png)

**Comment by Nirajn2311** [comment]
This issue is closed in #174
