### ISSUE TITLE
Feature Request: Progress Info in Super/Blocks' Titles

### ISSUE THREAD

**Issue by matthew-t-smith** [freeCodeCamp/learn#178]
####Summary

I would like to tackle this one myself, but essentially the issue is that you do not know which blocks or superblocks you have completed without expanding the trees out completely in your mapUi. Especially with the changes to the certificate programs and the addition of challenges, it becomes tedious to go back through and find out where you now lack challenges for completion.

####Feature Proposal

I simply propose appending a (4/10 blocks completed) for superblock titles and (25/27 challenges completed) for blocks' titles.

#### Closes Issue #17536 from `freeCodeCamp/freeCodeCamp`

This feature will need to be implemented under the `learn` repo. I closed my request under `freeCodeCamp` to move over here.

**Comment by Bouncey** [comment]
@matthew-t-smith Thanks for taking this up yourself.

Let me know if there is anything I can help you with
