### ISSUE TITLE
Mathjax is being displayed in challenges when there is no need

### ISSUE THREAD

**Issue by thatnini** [freeCodeCamp/learn#185]
[Mathjax](https://github.com/freeCodeCamp/learn/pull/150) was added to the site recently, but this appears to have a side effect of displaying mathematical symbols when there shouldn't be - just because a `$` is being used - and the text displayed has now become quite confusing!

See for example
[https://github.com/freeCodeCamp/freeCodeCamp/#17647](https://github.com/freeCodeCamp/freeCodeCamp/issues/17647) [https://github.com/freeCodeCamp/freeCodeCamp/#17633](https://github.com/freeCodeCamp/freeCodeCamp/issues/17633)
[https://github.com/freeCodeCamp/freeCodeCamp/#17641](https://github.com/freeCodeCamp/freeCodeCamp/issues/17641)
[https://github.com/freeCodeCamp/freeCodeCamp/#17620](https://github.com/freeCodeCamp/freeCodeCamp/issues/17620)

Is there a systematic fix for this, or are we literally going to have to go through each challenge by hand to resolve?

**Comment by johnkennedy9147** [comment]
@Bouncey @raisedadead 
Mathjax is picking up anything where there is text bounded by dollar signs.
eg 
in file:  `curriculum/challenges/02-javascript-algorithms-and-data-structures/es6.json`

this template literal
`Hello, my name is ${person.name}!<br>I am ${person.age} years old.`

becomes:
![image](https://user-images.githubusercontent.com/26827682/41650003-e76681ee-7474-11e8-83a7-57be70ac54b3.png)

The inline config on line 44 of `src/templates/Challenges/components/Side-Panel.js` seems to be the issue:
`tex2jax: { inlineMath: [['$', '$'], ['\\(', '\\)']] }`

I suggest we select alternate delimiters and amend the inline config and the rosetta code challenge json as necessary.

**Comment by Bouncey** [comment]
Thanks @johnkennedy9147, I have pushed changes to remove MathJax for now and opened an issue to reimplement it later. The build should only take another 15 minutes and your issue should be fixed. :+1:

**Comment by scissorsneedfoodtoo** [comment]
@thatnini, thank you for bringing this to our attention. I was the one who implemented MathJax recently to render the math functions in the Interview Prep section, but didn't think to check the SASS and other sections to see how they were affected. I'm very sorry for the inconvenience that it's caused!

I'll be working on a fix using @johnkennedy9147's suggestions, and will be sure to make sure the other sections of the site aren't affected this time around.
