### ISSUE TITLE
Reimplement MathJax

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/learn#187]
MathJax has been (soon to be) removed  in #186 because it was formatting challenge descriptions with no maths formula, making new concepts like SASS and RegEx nearly impossible to grasp because syntax was missing in the instructions.

See #185 for details

@scissorsneedfoodtoo is there a way to only implement MathJax for maths formula?

**Comment by johnkennedy9147** [comment]
@Bouncey 
The inline config on line 44 of src/templates/Challenges/components/Side-Panel.js seems to be the issue:
tex2jax: { inlineMath: [['$', '$'], ['\\(', '\\)']] }

I suggest we select alternate delimiters and amend the inline config and the rosetta code challenge json as necessary. 

documentation here: `https://docs.mathjax.org/en/latest/options/preprocessors/tex2jax.html#configure-tex2jax`

**Comment by scissorsneedfoodtoo** [comment]
@Bouncey, dang, I'm sorry about that. Didn't think to check if SASS and other things would be affected.

@johnkennedy9147 is exactly right. I think for now it's better to remove that line and use the default config, which should look for `$$...$$` delimiters rather than single $'s.

**Comment by Flarp** [comment]
What about [Katex](https://khan.github.io/KaTeX/)?

**Comment by tchaffee** [comment]
@scissorsneedfoodtoo Are you working on this? Any progress?

**Comment by scissorsneedfoodtoo** [comment]
@tchaffee, yes, I've been working on this slowly. Been playing around with both Katex like @Flarp suggested and MathJax, trying to see which is faster/better supported.

Using the `$$...$$` delimiters now and going through the challenges trying to make sure it doesn't break any other challenge descriptions.

**Comment by tchaffee** [comment]
@scissorsneedfoodtoo That's good news. In terms of delimiters, is there any reason to not choose a delimiter so specific that it would be almost guaranteed to be unique? `$$inLineMathBegin\...$$inLineMathEnd\`?

**Comment by scissorsneedfoodtoo** [comment]
@tchaffee, that's a good point. It's mostly just a matter of how much can be done quickly and easily. I could certainly change the delimiters to something like `$$inlineMath$$` and retest.
