### ISSUE TITLE
Console not displaying return values

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#189]
@JamesStaffordCoyte commented on [Fri Jun 01 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17356)

#### Describe your problem and - if possible - how to reproduce it
The problem is with all algorithm problems. The test runs against all the test values but the console does not return the actual value you ask it to return. I like to test certain return values either by returning them or by console.log(); but with the recent update this doesn't seem to work at all so I have 0 idea what I might be returning. I'd rather see see what it does return, not what it should. I cannot debug.  This makes bugs/errors incredibly difficult to solve.

#### Add a Link to the page with the problem
All Algorithm Challenges

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66
* Operating System: MacOS

#### If possible, add a screenshot here
![screen shot 2018-05-31 at 3 44 55 pm](https://user-images.githubusercontent.com/26333632/40812252-af836778-64e9-11e8-9560-8b7350ad8da4.png)

---

@raisedadead commented on [Fri Jun 01 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17356#issuecomment-393711393)

Thanks for the report. As a work around while we fix this you can look at the DevTools console of your browser and still see the console.log statements?

![image](https://user-images.githubusercontent.com/1884376/40813004-525b75e6-6556-11e8-8ea7-46cffbe1caca.png)

That said we definitely need to pass the log back to the in app log area.

---

@JamesStaffordCoyte commented on [Fri Jun 01 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17356#issuecomment-393713656)

Thanks raisedadead. That's what I've been using. Just wanted to know if there were plans to fix this. Glad to here there is. Thanks again.

**Comment by ojeytonwilliams** [comment]
Hey. I've been looking at this and I think I'm getting somewhere.

I've managed to tweak the code and now spits out something like this:
```
// running tests 
goodness
me
// failed tests
Your regex should match freeCodeCamp
Your regex should match FreeCodeCamp
...
// tests completed
```
when there are two logs in the editor.  When there are no logs, you just get
```
// running tests 
// failed tests
Your regex should match freeCodeCamp
Your regex should match FreeCodeCamp
...
// tests completed
```

Does that seem about right?

**Comment by ktajpuri** [comment]
I think it would make more sense to have the console output in a separate section. We can have the logic that the section will only be visible if some output is there in the console. Something like
```
// running tests 
// failed tests
Your regex should match freeCodeCamp
Your regex should match FreeCodeCamp
...
// tests completed

//Console Output
goodness
me
```

**Comment by tchaffee** [comment]
@Bouncey since @ojeytonwilliams is working on this, could we assign him to the issue and remove the help wanted label?

**Comment by ojeytonwilliams** [comment]
@Bouncey Since my fix had to be removed, should this be re-opened?
