### ISSUE TITLE
Feature Request: Autofocus editor when a new challenge is rendered

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/learn#192]
@w96k commented on [Fri Jun 22 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17688)

#### Describe your problem and - if possible - how to reproduce it
I use mostly keyboard and its quite annoying to focus on text area after completing each task. After each task, I need to grab a mouse :(

#### Add a Link to the page with the problem
Any task

#### Tell us about your browser and operating system
Firefox 52
Debian 9

**Comment by Bouncey** [comment]
@w96k would a hot key work for you?

I think we had `e` before.

**Comment by w96k** [comment]
@Bouncey Yeah looks like "e" works, but I didn't know about that hotkey. I think it's better to autofocus anyway like Google does. FCC focuses on completing tasks, not searching. Thanks for the reply.

**Comment by Bouncey** [comment]
Oh, now i understand what you mean. Issue title changed to reflect the request

**Comment by ktajpuri** [comment]
I would like to work on this one.

**Comment by w96k** [comment]
Good job :+1:
