### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by Bigj2987** [freeCodeCamp/learn#193]
Im not sure why,but everytime I try to access any sort of assignment/challenge "Comment your Code in Javascript" for example the only thing that loads is a whitepage. I tried switching browsers to Safari and all I get is "Safari can't open the page" I feel kind of stupid because,I actually skipped work(I seldomly have days off) today to completely focus on coding today.
I use google Chrome as my main browser 
Version 49.0.2623.112 I'm on a mac.

**Comment by scissorsneedfoodtoo** [comment]
@Bigj2987, so sorry to hear about your issue. I'm not in front of my laptop at the moment, but the site seems to work fine on my phone, including the challenge you mentioned.

Here's the direct link for reference: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code

Would you happen to have any ad blockers or similar extensions installed on your browsers? Those can cause problems with the site. If so, could you disable them and try loading the page again?

**Comment by Bigj2987** [comment]
I have disabled all extensions on my google chrome browser,and I get the same result a blank white page. I was using this website actively a month ago,and it was working fine then.

**Comment by huyenltnguyen** [comment]
@Bigj2987 Could you check the browser console if there is any error? Also, I notice that you are not using the latest version of Chrome, is it okay if you update it? There are some new challenges in the curriculum that require new technology (React stuff), so maybe your Chrome version doesn't support it.

**Comment by Bouncey** [comment]
@Bigj2987 It seems you are on a super old version of chrome, try updating and see if it helps.

![Current stable versions of Chrome across OS's](https://user-images.githubusercontent.com/18572518/41818430-02dba6f4-77a7-11e8-90b8-f15c1ff51ec9.png)

**Comment by Bouncey** [comment]
@Bigj2987 Are you still having issues?
