### ISSUE TITLE
Night Mode Editor styling issues

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/learn#204]
Couple of issues with night mode on Learn:

Cursor hard to see in editor. Black on dark grey.

No visual indication at all of selected text - in below screenshot I have selected function minusSeven
image

![image](https://user-images.githubusercontent.com/26827682/42100963-9b68e452-7bb9-11e8-9f28-48fae3be047f.png)

**Comment by raisedadead** [comment]
The theme is added programatically here:
https://github.com/freeCodeCamp/learn/blob/2d6beb7bceea7ad1b715e2a838577171c7f5e9c2/src/layouts/index.js#L99

But we should exclude the `.night` class from being extended/added programatically here:

https://github.com/freeCodeCamp/learn/blob/2d6beb7bceea7ad1b715e2a838577171c7f5e9c2/src/templates/Challenges/classic/Editor.js#L98

We should rather use `vs-dark` to configure the editor here:

https://github.com/freeCodeCamp/learn/blob/2d6beb7bceea7ad1b715e2a838577171c7f5e9c2/src/templates/Challenges/classic/Editor.js#L105

**Comment by raisedadead** [comment]
Update:

The only fix needs to be done is to add the `vs-dark` here when the theme is night

https://github.com/freeCodeCamp/learn/blob/2d6beb7bceea7ad1b715e2a838577171c7f5e9c2/src/templates/Challenges/classic/Editor.js#L105
