### ISSUE TITLE
Upcoming Lessons unreadable in Night Mode 

### ISSUE THREAD

**Issue by anku255** [freeCodeCamp/learn#209]
**Screenshot**:

![image](https://user-images.githubusercontent.com/22813027/42124807-0d346a98-7c87-11e8-81a3-2be7ae6eeaa5.png)

**Link to the Page(s)**:

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5
https://learn.freecodecamp.org/responsive-web-design/basic-css

This bug is present in every section.

**Browser Information:**
- Browser Name: Chrome
- Browser Version: 67.0.3396.99
- Operating System: Windows 10

**Comment by anku255** [comment]
Upon some inspection, I found two quick ways of fixing this.

1. Remove the follow CSS selector
```css
.night a {
  color: #f8f8f8;
}
```

See screenshot below:
![image](https://user-images.githubusercontent.com/22813027/42124891-42dec420-7c89-11e8-9761-fafa88da1e3a.png)





2. Add a  new CSS selector

```css
.intro-toc a {
    color: #006400;
}
```

See screenshot below:
![image](https://user-images.githubusercontent.com/22813027/42124896-51d76c48-7c89-11e8-9965-97250c7721f8.png)



@raisedadead @Bouncey Your thoughts on this?

**Comment by raisedadead** [comment]
Yes please make a PR.

**Comment by anku255** [comment]
@raisedadead Great! I am going with the option 2 as I think that's better.

**Comment by anku255** [comment]
@raisedadead I have created a PR #210. Please take a look.
