### ISSUE TITLE
Unreadable code blocks in night mode

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#211]
![image](https://user-images.githubusercontent.com/1884376/42125767-5938f194-7c9a-11e8-9838-9d7025ab3f01.png)

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/

**Comment by gforce2k5** [comment]
I can think of 2 approaches to this issue, 1 removing the backgrounds from the rows or changing the background of the code block

**Comment by renojvarghese** [comment]
I think option two is better. Fits the theme a bit better. The biggest problem was the text shadow that made the content blurry

**Comment by renojvarghese** [comment]
Sorry @gforce2k5 I think I beat you to it. I was working on it this morning, and I forgot to claim it.

**Comment by gforce2k5** [comment]
@renojvarghese It's ok
