### ISSUE TITLE
When tests are running, SASS hasn't been compiled yet

### ISSUE THREAD

**Issue by ValeraS** [freeCodeCamp/learn#216]
Issue:
freeCodeCamp/freeCodeCamp#17762

Possible solution: 
if in function runTests from src/client/frame-runner.js increase delay (on line 88), then tests pass.

**Comment by Bouncey** [comment]
Solid find @ValeraS, care to make a PR?

**Comment by ValeraS** [comment]
@Bouncey I am not sure about that solution. Can we know when preview is completed and then run tests?
