### ISSUE TITLE
Grammar, spelling, spacing issues in HelmetJS intro

### ISSUE THREAD

**Issue by CharmedSatyr** [freeCodeCamp/learn#234]
**Describe the bug**
Various grammar/spelling/spacing issues in the second and third paragraphs of the HelmetJS introduction.

https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/

Specifically, corrections needed include:
1. Comma after the subordinate clause "After completing each challenge"
2. Capitalize Glitch in "public glitch"
3. Comma after "Optionally"
4. Comma after "... you may choose to write your project on another platform"
5. Correct spelling of "publicaly" -> "publicly"
6. Add another `<br>` before "Start this project"

**Screenshots**
![screenshot from 2018-07-12 12-20-25](https://user-images.githubusercontent.com/16056963/42649114-59e115e4-85ce-11e8-86cd-db1f625ea120.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04 LTS
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] 0.23.31

**Additional context**

**Comment by ravikishorethella** [comment]
@Thibaut @CharmedSatyr Can I work on this?

**Comment by ravikishorethella** [comment]
one more fix - "unintentially"
