### ISSUE TITLE
404 error, page not found on react challenge.

### ISSUE THREAD

**Issue by chaitanyagiri** [freeCodeCamp/learn#236]
In the Front End Libraries Certification: React Challenge there is a [challenge](https://learn.freecodecamp.org/front-end-libraries/react/introducing-inline-styles) named 
> Introducing Inline Styles

in which there's a link to an [article](https://learn.freecodecamp.org/define-an-html-class-in-jsx)  and when I click in the link it redirects me to a 404 page. That means the page does not exist anymore.

**Comment by wadleo** [comment]
I think that link was meant to take the user to this challenge instead

https://learn.freecodecamp.org/front-end-libraries/react/define-an-html-class-in-jsx/

@QuincyLarson can you attest to this, so I can send a patch?

**Comment by johnkennedy9147** [comment]
@wadleo @chaitanyagiri The directory structure was changed so there are likely a number of stray links pointing to wrong locations. The link @wadleo supplied is the correct replacement.

**Comment by wadleo** [comment]
Ok @johnkennedy9147, thanks for the confirmation. I will send a patch in some few hours, let me rush to church now.

**Comment by wadleo** [comment]
On research to fix this broken link, I found the problem in the curriculum repo, so I will send a patch there shortly.

**Comment by wadleo** [comment]
Here is the link to the PR that fixes it on the curriculum repo https://github.com/freeCodeCamp/curriculum/issues/155

**Comment by Bouncey** [comment]
Thanks @wadleo, closing as it is being tracked in the curriculum repo
