### ISSUE TITLE
Quote not visible clearly in 404 error page in Night Mode

### ISSUE THREAD

**Issue by chaitanyagiri** [freeCodeCamp/learn#237]
The quote displayed on the 404 error page is not visible properly in Night mode. Please refer to the screenshot attached below.
![screenshot from 2018-07-15 08-51-59](https://user-images.githubusercontent.com/26071627/42730862-718fcc42-881e-11e8-85d9-1dcf27baf84c.png)

**Comment by wadleo** [comment]
![gnome-shell-screenshot-a8rvlz](https://user-images.githubusercontent.com/11006276/42731935-8bd700e8-880f-11e8-890c-55473497c9f4.png)

I think this may do here, I will look into it later today or @chaitanyagiri are you already working on this?
