### ISSUE TITLE
Accept value 0 without measure unit

### ISSUE THREAD

**Issue by rzelnik** [freeCodeCamp/learn#245]
In this lesson:
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-movement-using-css-animation
... I put 0 as a value in this code:
`@keyframes rainbow { 0% { ... left: 0; }`

It shows me this error message:

> // running test
The @keyframes rule for 0% should use the left offset of 0px.
// tests completed

Value '0' should be accepted besides '0px', because zero value doesn't need a unit of measurement. Zero is always zero.

**Comment by tchaffee** [comment]
@rzelnik Thank you for reporting this issue. Could you please report the issue in the correct repo https://github.com/freeCodeCamp/curriculum/. It is related to issue https://github.com/freeCodeCamp/curriculum/issues/166.

Thank you!
