### ISSUE TITLE
Carets in the map shrink in size when the associated text wraps

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/learn#25]
![anim](https://user-images.githubusercontent.com/18572518/38955233-f494fcce-434b-11e8-9ccc-00cd555863ac.gif)

**Comment by Simbaxo** [comment]
Is your goal to keep the carets visible when the map shrinks?

**Comment by Bouncey** [comment]
Hi @Simbaxo :wave: 

The idea is that they remain the same size at all times.

**Comment by Simbaxo** [comment]
Oh okay. I'm fairly new to this but I would like to give this a shot!

**Comment by Bouncey** [comment]
Awesome! Thanks @Simbaxo :+1:
