### ISSUE TITLE
Random quotes for 404 page flickers

### ISSUE THREAD

**Issue by ktajpuri** [freeCodeCamp/learn#256]
If you land to **404 not found page** in learn site,[ https://learn.freecodecamp.org/404]( https://learn.freecodecamp.org/404) , It will show the 404 image and a random quote. As soon as you start reading the quote it changes to another quote !
It appears due to some bug, page is showing one quote first, then randomly selecting another quote after 1 second. Bad user experience.
![ozklrhjojw](https://user-images.githubusercontent.com/10725893/43387641-3d6856bc-93e7-11e8-80e9-3a1844ea736a.gif)

**Comment by ktajpuri** [comment]
Looking at the compoent , https://github.com/freeCodeCamp/learn/blob/master/src/pages/404.js, I think the issue is that this is a functional stateless component, it gets rerendered on every state change of parent. First time when it loads, user state is not present, after the user state is set it  re renders and displays another random quote. We will have to make the 404 component as pure component instead of a functional statless component. I have created a quick fiddle to demonstrate the bug and the fix. 

https://jsfiddle.net/2xph3tgk/

**Comment by wadleo** [comment]
@ktajpuri are you sending a patch to fix it?

**Comment by ktajpuri** [comment]
@wadleo  you can work on it if you want :) Already have an open PR for another issue.

**Comment by wadleo** [comment]
@ktajpuri @raisedadead  what if we could change the quote after a couple of seconds, say 5-10 seconds, what do you guys think? @QuincyLarson

**Comment by raisedadead** [comment]
> what if we could change the quote after a couple of seconds, say 5-10 seconds, what do you guys think?

Since its just a 404 page. I think we do not need to update the code periodically.
That said please feel free to fix the flicker issue.

Thanks.

**Comment by QuincyLarson** [comment]
@wadleo I agree - there's no need to update the quote. It can just show a single quote.

@ktajpuri Thanks for discovering this problem. Would you be interested in digging in and trying to fix it?

**Comment by wadleo** [comment]
ok, I will send the fix shortly, thanks for the input.

**Comment by ValeraS** [comment]
Problem not only in the component but in a static 404.html page. It is generated by Gatsby. If we land to 404 not found page, we get the first quote which always the same. After state change, the component is re-rendered and we get a random quote.

We need to do static 404.html without a quote and that a quote appears only on the client side.

**Comment by wadleo** [comment]
Hi @ValeraS please if you can provide more details on how to achieve this with Gatsby, I will really appreciate that. I am new here and trying to get my feet wet, if you get what I mean, thanks.

**Comment by ValeraS** [comment]
Hi @wadleo!

In brief: in the component, we set the initial state not to show a quote's block and then in componentDidMount() set the state to show the quote's block. In render(), we show the quote's block depending on the state.

componentDidMount() is invoked after a component is inserted into the DOM. The server environment has no DOM, the browser provides the DOM. So, componentDidMount() is invoked only on the client side.
