### ISSUE TITLE
"Map is not a function" in a Rosetta Code problem

### ISSUE THREAD

**Issue by pom421** [freeCodeCamp/learn#270]
Hello,

Maybe it's me and my frustration about the editor of FCC but the editor sends me an error and I don't know why.

It's for https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/100-doors/.

When i put an answer with a `numDoors.map`, that says `numDoors.map is not a function`.
But when I just add a console.log (and don't hit the Run tests button), then I see that the code is run but I have always the `numDoors.map is not a function`.

My code is something like (with ... to obfuscate the code a little) : 

```
function getFinalOpenedDoors (numDoors) {
    
    for (let i = 1; i <= ...; i++) {
      numDoors = numDoors.map((door, index) => ...)
    }
  
    return numDoors
  }
  
  const res = getFinalOpenedDoors(inputs)

  res.map((elt, i) => console.log(i, elt))

```

My code seems good when i test it on Visual Code...

**Comment by ValeraS** [comment]
@pom421 numDoors is the number.

**Comment by pom421** [comment]
Are we supposed to invoke the function?

Because when I try 

```
function getFinalOpenedDoors (numDoors) {
    console.log("result :", numDoors, ":")
    console.log("instanceof" + numDoors instanceof Array)
}
```

nothing happens...

**Comment by ValeraS** [comment]
You can view log in the console from the Developer tools
![image](https://user-images.githubusercontent.com/10867286/44328550-833b7280-a46a-11e8-8a62-441ddc99b3f9.png)

**Comment by pom421** [comment]
Thanks @ValeraS! It's a really game changer to have a mean to roughly debug. 

It's still confusing in FCC, that the console.log is sometimes displayed in the running test panels and sometimes it isn't. It's not very user friendly.

Why do we need the numDoors parameter? The exercice explains a problem with 100 doors, not a generic problem with more.  And there is no complete example of the call of this function, which could be useful for a dev.
