### ISSUE TITLE
News page link not in navigation bar on learn.freecodecamp.org

### ISSUE THREAD

**Issue by jarikmarwede** [freeCodeCamp/learn#281]
The link to the news page that has been added to the navigation bar on www.freecodecamp.org is not added to the navigation bar on [learn.freecodecamp.org](https://learn.freecodecamp.org).

![screenshot_2018-09-01 welcome to learn freecodecamp 1](https://user-images.githubusercontent.com/33765260/44947990-fbfce000-ae15-11e8-96e2-c34a3cae6c03.png)
![screenshot_2018-09-01 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/33765260/44947992-fe5f3a00-ae15-11e8-93ec-335323adda4a.png)

**Comment by Nirajn2311** [comment]
I can take this up once someone has approved it.
