### ISSUE TITLE
Stub superBlock index pages

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/learn#30]
Much like we moved the introduction challenges to markdown, see `/responsive-web-design/basic-css` for an idea of what I am talking about, We would like to so the same to `/superBlock` routes. 

Step one is to stub the pages until we have a better idea as to what they will look like and how they will function.

- Each top-level folder in the `/src/introductions` directory should have and `index.md` file. The contents of this markdown file should be

```sh
---
title: <Title of the superBlock (Title Case)>
superBlock: <Title of the superBlock (Title Case)>
---
This is a stub introduction for <Title of the superBlock (Title Case)>
```

- In `/src/utils/gatsby`, the `createIntroPages` function will need to be changed to check for the presence of `block` in the values passed to it. If `block` is falsey, we should create the page with a different component. This is the current `Intro` component is not compatible with the what we have in the `superBlock` stubs.

- Create a `SuperBlockIntro` component in `/src/templates`, all we want it to do for now is render the html passed to it. See the `Introduction` component to see how the `graphql` query is structured and how the data is passed in as props.

- Most importantly, have fun!

If you get stuck, reach out to us and ask all the questions! No question is a silly question if you don't know the answer.

**Comment by Simbaxo** [comment]
I'm going to attempt this one as well.

**Comment by tchaffee** [comment]
@Simbaxo are you still working on this? If not, I can give it a try.

**Comment by tchaffee** [comment]
I'm blocked by issue https://github.com/freeCodeCamp/learn/issues/31 and as soon as we can get that figured out I'll take a look at this.

**Comment by Bouncey** [comment]
Hi @tchaffee, how are things going with this PR? Can I help in any way?

**Comment by tchaffee** [comment]
@Bouncey Thanks for the reminder. I got caught up in other work, but I can prioritize this now. I'm a little confused about exactly what has to be done. Can you hop on gitter or somewhere else at some point to help?

**Comment by tchaffee** [comment]
@Bouncey Can this issue be closed now or is there more work to do?

**Comment by Bouncey** [comment]
Thanks @tchaffee :+1:
