### ISSUE TITLE
Swap out the copy-webpack-plugin for monaco-editor-webpack-plugin

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/learn#36]
We edit the webpack config though `./gatsby-node.js`, near the bottom of the file

**Comment by Bouncey** [comment]
So at the minute, in the depths of `gatsby-node.js` we are using a plugin called `CopyWebpackPlugin` which copies js/css files that the monaco editor uses into the public dir.

This new plugin I think either does the same job and is supported by the MS Monaco team, of it offers the files up to webpack to include them in the bundle.

Testing would be just running locally and seeing that the editor still works

**Comment by tchaffee** [comment]
I tried working on this today, but I'm blocked by issue #86.

**Comment by tchaffee** [comment]
@Bouncey I gave this a shot and am stuck. I keep getting errors where the stack trace points to webpack and properties of `compiler.hooks` being non-existent. When I dug a little deeper I noticed that gatsbyjs requires `"webpack": "^4.5.0"` and gatsbyjs only supports webpack v1. Quite a gap.

One of the problems seems to be around a change to Plugins, which "should use Compiler.hooks.xxx.tap(<plugin name>, fn) now" as of webpack v4. You can read more about the [breaking changes for webpack v4 here](https://github.com/webpack/webpack/issues/6064). 

Even [v2 of gatsby](https://github.com/gatsbyjs/gatsby/issues/2641) (still in alpha) only supports webpack v3. 

So I'm not sure where to go with this. I think for now the `CopyWebpackPlugin` is the best solution unless you have other ideas.

**Comment by Bouncey** [comment]
Oh ok, I didn't know it required webpack v4, thanks for investigating @tchaffee.

Deferring until we hit gatsby v2
