### ISSUE TITLE
possible error in challenge description

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#42]
Challenge: "Basic HTML and HTML5 - Create a Set of Radio Buttons"
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons

Here is the relevant text in the description for this challenge:

> Each of your radio buttons should be nested within its own label element. Wrapping an input element inside of a label element makes the label text clickable.

It is NOT necessary to wrap an input element inside of a label element to make the text clickable as long as there is a `for` field on the label that matches the `id` of the input. The recommendation on fCC is contrary to what is shown at MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

It works either way so this is not necessarily an error but I think it is best to change this to go along with MDN.

**Comment by beaucarnes** [comment]
Same for checkboxes. This should be changed as well to match best practices shown on MDN.

**Comment by Bouncey** [comment]
Thanks @beaucarnes! The seed files are going to remain in freecodecamp/freecodecamp, so any edits to the challenges should be handled over there. We are working on pulling them in through `npm`.

Thanks for checking out out learn!

**Comment by raisedadead** [comment]
@beaucarnes if you could open up the issue there then it would be great.
