### ISSUE TITLE
need to fix typo and add info about env in the Contributing file.

### ISSUE THREAD

**Issue by texas2010** [freeCodeCamp/learn#44]
When I follow the step to step.
after I run the `yarn develop`. I went to check browser. I checked the site. I got white page and an error in the console.

![screen shot 2018-05-17 at 3 34 17 pm](https://user-images.githubusercontent.com/9701609/40202547-f3e197c6-59e7-11e8-80ed-760b70cfe955.png)

I didn't realize, I have to create env file. since set up the step to step didn't tell us, we need to do it before run `yarn develop`

more like we need to info them about it. as the user use learn repo first time.

about typo, 
4. `git branch -b <your-branch-name>` is typo.
i think correct info is 4. `git checkout -b <your-branch-name>`

**Comment by texas2010** [comment]
I think the first-timers can do this. I am sure this is simple to fix.

**Comment by absolitudo** [comment]
I think it's worth mentioning here that some of the commands require gatsby to be globally installed, which is not included in the instructions either.

**Comment by ekaoddlass** [comment]
Hi, I would like to try and work on this issue please. How do I claim it?

**Comment by Bouncey** [comment]
It is yours @ekaoddlass 👍

**Comment by ekaoddlass** [comment]
PR submitted and merged -- this was my first PR!

Out of curiosity though, I did not copy the sample.env file (confirmed with `ls` that my local clone does not consist of .env file) but I could run `yarn develop` without problem. Does it depend on your machine's global setting whether you need .env or not?

**Comment by SMM-dev** [comment]
@ekaoddlass Grats on the first PR :)
There was an extra word "branch" in your changes so I modified the file a bit more.
As for the samle.env file, I got an error when trying to copy it but was still able to run the build without it... so it may just be a necessary step for certain situations only.

**Comment by Bouncey** [comment]
Closed via #70
