### ISSUE TITLE
Test results overlap onto the preview area when panes at default size

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#51]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property
Issue Description
The test results are overlapping the preview area at the default pane size. The ❌ or ✔️ appear to be too large, making either:

1) the text squished together
![image](https://user-images.githubusercontent.com/22984739/40248592-727b04ee-5a9e-11e8-995c-b081bb4a8aa2.png)

2) the text to overlap into the preview section of the pane 
![image](https://user-images.githubusercontent.com/22984739/40248616-83d833b0-5a9e-11e8-9028-86aabaa193df.png)

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

**Comment by SMM-dev** [comment]
After playing around with Firefox's page inspector, I think I've isolated the issue to the **.test-result {height}** rule in the _test-suite.css_ file.
So how do I go about running my local, cloned copy of the application to test my changes before making a PR?
Obviously I'm new to this, so any help/advice is appreciated.

**Comment by ekaoddlass** [comment]
@SMM-dev See https://github.com/freeCodeCamp/learn/blob/master/CONTRIBUTING.md, I just updated it with an extra step (copy .env file -- I actually could run this on localhost without doing it but apparently some others could not). Also, it may be necessary to have Gatsby installed globally.

**Comment by SMM-dev** [comment]
@ekaoddlass thanks! I'll read up and start working on a fix asap.
