### ISSUE TITLE
Pasting into editor menu text is too dark - visibility issue

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#52]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

Issue Description
Right clicking into the editor to paste text from lesson, the menu items are hard to see as its green on dark grey

![image](https://user-images.githubusercontent.com/22984739/40249828-3e7b95b0-5aa2-11e8-9ed1-64756b345893.png)

**Comment by Bouncey** [comment]
That is handled by the Monaco editor, I'm not sure how much control we have over this.

**Comment by ekaoddlass** [comment]
It can be fixed by adding one line of CSS to **templates/Challenges/classic/classic.css**

`.monaco-menu .action-label {
  color: #a2bd9b;
}`

Is this an acceptable approach? Shall I create a PR for this?

Cheers!
