### ISSUE TITLE
Test Results in Preview Pane showing passed on incorrect code

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#54]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements
Issue Description
The test results in the preview pane are showing as all passed but the code is incorrect. The editor console is showing the correct information. 

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

![image](https://user-images.githubusercontent.com/22984739/40250428-410e2b9c-5aa4-11e8-8bab-0cd67e9e02f7.png)

**Comment by Bouncey** [comment]
The code looks good for the href test you pointed out @mstellaluna

**Comment by mstellaluna** [comment]
@Bouncey  I am closing this out due to being my error , I didn't notice the test results on the preview pane go past and I had to scroll down in that section. 😄
