### ISSUE TITLE
Unable to vertically resize code / tests frames

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#56]
The mouse curser indicates that it should be possible to vertically resize the code / test frames. However, it is not possible. For a better user experience for people on small screens, this should be possible. See gif below.

![fcc3](https://user-images.githubusercontent.com/1513130/40251326-05bcfac0-5aa7-11e8-9121-c2ae346735b5.gif)

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, I noticed the same thing recently. I think I found a solution we can implement similar to the one [here](https://github.com/superRaytin/react-monaco-editor/issues/53) and am working on a PR now.

**Comment by Bouncey** [comment]
Awesome @scissorsneedfoodtoo!
