### ISSUE TITLE
Selecting item in curriculum map should close modal

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#57]
Selecting item in curriculum map should close map modal. Currently it updates the page but the modal stays open.
![fcc4](https://user-images.githubusercontent.com/1513130/40251882-91ac9b3e-5aa8-11e8-87e8-be79f32f53e9.gif)

**Comment by Bouncey** [comment]
Definitely  fixed this in #50.

Please try a hard refresh and attempt it again 👍

**Comment by beaucarnes** [comment]
Not fixed. Am I testing the correct site?
https://deploy-preview-45--freecodecamp-learn.netlify.com/

**Comment by beaucarnes** [comment]
Fixed now that I'm testing on the correct url!
