### ISSUE TITLE
Example link in lesson text opens to FCC website in same tab

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#58]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

Issue Description
In the lesson text opens to freecodecamp.org website in the same tab. My suggestion is to have it open to a new tab so the camper does not lose lesson they are on. 

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

![image](https://user-images.githubusercontent.com/22984739/40252295-eeac3af0-5aa9-11e8-920d-0e81691fd9e4.png)

**Comment by beaucarnes** [comment]
Normally I agree that links should open in a different tab but in this case I don't think it should open to a new tab. This is an example of the type of link that does not open into a new tab. If it opened into a new tab, it would be using HTML that is different than the HTML that the lesson text says it is an example of.

**Comment by mstellaluna** [comment]
@beaucarnes Agreed, although if a camper though decides to click on that link as it is an active link, it will bring them to the freecodecamp.org website in the same tab they are viewing the lesson.

**Comment by Bouncey** [comment]
We could change the example to use a `_blank`. Ideally, we don't want to take users away from their lesson. I don't think there will be many queries over the `target` attribute.

Notes to contributors, this should be fixed in the freecodecamp/curriculum repository, the code is not held in learn.

**Comment by beaucarnes** [comment]
I agree with both of you now. I noticed that `target="_blank"` is introduced in the previous lesson so hopefully people will understand when it is used in this lesson.

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/curriculum #18](https://github.com/freeCodeCamp/curriculum/issues/18) via [**ZenHub**](https://www.zenhub.com/)
