### ISSUE TITLE
Links to Glitch starter project should open in new window

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#59]
Some challenges link to a Glitch starter project. The link opens in the same window. It would be more user-freindly if the link opened in a new window/tab. Most people clicking on that link will want the fCC page to still be open so they can submit their project. This also applies to GitHub link.

Example url: https://deploy-preview-45--freecodecamp-learn.netlify.com/information-security-and-quality-assurance/advanced-node-and-express/use-a-template-engines-powers

Image of one page that has the link:

![image](https://user-images.githubusercontent.com/1513130/40252276-e4c192ba-5aa9-11e8-9a2e-5e5fe6a21c5e.png)

**Comment by nikrb** [comment]
anchor tags need `target="_blank"`.
Few dozen instances in half a dozen files:
./challenges/06-information-security-and-quality-assurance/quality-assurance-and-information-security-projects.json
./challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
./challenges/06-information-security-and-quality-assurance/testing-with-chai.json
./challenges/06-information-security-and-quality-assurance/helmetjs.json
./challenges/05-apis-and-microservices/apis-and-microservices-projects.json
./challenges/08-coding-interview-prep/take-home-projects.json

**Comment by tchaffee** [comment]
@Bouncey can this be closed? This really belongs on the curriculum repo and the PR was already closed.
