### ISSUE TITLE
Many introductory challenges missing from learn curriculum

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#60]
The challenge titled "Introduction to the Managing Packages with npm Challenges" is in _beta_ but not in _learn_. Many other introductory challenges are also missing. They are important because they introduce Glitch which is referred to in many other tasks. 

Many tasks start with the line, "As a reminder, this project is being built upon the following starter project on Glitch, or cloned from GitHub." Without this missing task, we are reminding people of something we never told them.

See screenshot with learn and beta side-by-side. There are many more missing introductions not shown.

![image](https://user-images.githubusercontent.com/1513130/40252892-cd3223b0-5aab-11e8-865b-cc5baa8e1dea.png)

**Comment by Bouncey** [comment]
The introduction challenges are now available under `/:superBlock/:block` so your example would be `/apis-and-microservices/managing-packages-with-npm`

I agree that this should be clearer. If a camper is progressing through the challenges, then they will hit these introduction challenges as part of the progression
