### ISSUE TITLE
Glitch starter project should have all references to 'HyperDev' changed to 'glitch'

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#61]
This issue is not actually in the codebase but it is part of the curriculum. The Glitch starter project should have all references to 'HyperDev' changed to 'glitch'. @QuincyLarson may have to do this one and it may not be high priority.

![image](https://user-images.githubusercontent.com/1513130/40253595-59c3a0d6-5aae-11e8-8f80-a5122c1b712c.png)

**Comment by tchaffee** [comment]
@Bouncey I think this should be closed and a new issue be opened on the curriculum repo?
