### ISSUE TITLE
Test suite for projects is not working

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#63]
The test suite on projects is not working. Projects pass no matter what. This seems to apply to all projects.

In the example below, I should not have passed by entering 'http://freecodecamp.org'.

![image](https://user-images.githubusercontent.com/1513130/40254825-ef141ea0-5ab2-11e8-918e-8fa8df9e006e.png)

**Comment by Bouncey** [comment]
Projects do not have any test suits. The solutions to projects are public if the camper has claimed and enabled public viewing of their certifications.

**Comment by Bouncey** [comment]
Closing as this is expected behaviour.
