### ISSUE TITLE
Assert tests appear in the preview window while typing in editor

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#66]
Challenge Name
https://learn.freecodecamp.org/responsive-web-design/basic-css/prioritize-one-style-over-another

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

Issue Description
The assert tests show up in the preview pane while typing in the editor. It disappears once the complete needed code is written. 

The message is actually quite long.. a small screenshot has been provided
![image](https://user-images.githubusercontent.com/22984739/40261232-737272f4-5acd-11e8-8b60-c0188db33831.png)

**Comment by Bouncey** [comment]
That isn't the assert tests, that looks like the test runner we use inside the test-frame/preview. I have never seen that before. 

@mstellaluna Was it in the preview or editor? Did you type anything weird? Does it happen all the time?

**Comment by mstellaluna** [comment]
@Bouncey ah, sorry i didnt know what it was. It was in the preview window. It started blank, I started typing, as I am typing this shows up in the preview pane, once I'm done typing it's gone and the preview windows what it supposed to.

here's the breakdown:

1) lesson loads, preview area is empty white area
2) as I'm writing .pink-text, the preview area flashes and changes to a black background with Hello World in green
3) as I am writing to create a class in h1 element, the preview pane flashes again and test runner shows up. 
4) when I finish adding the class, the test runner disappear

I am able to re-produce this on a different computer, within chrome

Here is a group of screenshots:

On lesson load:
![image](https://user-images.githubusercontent.com/22984739/40268875-8a0fed04-5b43-11e8-88fa-d0456a1441a6.png)

While creating the pink-text css class:
![image](https://user-images.githubusercontent.com/22984739/40268883-b88a68a8-5b43-11e8-83d5-79f43bf9f53e.png)

While adding the pink-text class to h1 element:
![image](https://user-images.githubusercontent.com/22984739/40268892-d679523e-5b43-11e8-9b55-293c08095d8a.png)

Lesson completed without running the tests:
![image](https://user-images.githubusercontent.com/22984739/40268895-ed0f35c2-5b43-11e8-8bb2-e7e4191193c1.png)

**Comment by mstellaluna** [comment]
@Bouncey so, to add something further. If I am typing quickly it doesn't show up in the preview pane. if I am typing class=" and I stop for a second (let say to check the name of the css class again) or type slowly, it shows up. not sure if this help or not.

**Comment by Bouncey** [comment]
Grizzly!

Nice find @mstellaluna :+1:

**Comment by Bouncey** [comment]
I cannot reproduce on Ubuntu in FF or Chrome, I think it is a windows thing

**Comment by mstellaluna** [comment]
@Bouncey I have a VM with RHEL Developer Edition and one with Ubuntu. do you want me to try it there to see if I can re-produce on Linux?

**Comment by Bouncey** [comment]
Sure, anything can help

**Comment by mstellaluna** [comment]
@Bouncey I tried it on RHEL Developer Edition 7.5.0 with FF ESR 52.7.0 (64-bit)  and with Ubuntu 18.04 LTS with FF Quantum 59.0.2 64-bit, I'm getting the issue on both.

I was able to pin-point exactly when this shows up.

When you are typing in the class pink-text into the element and stop at the open quotation, the test runner  will show up in the preview pane and stay there until the quotation is closed.

This happens on linux and windows in both chrome and FF.

Hope this helps. 

Below are the screenshots explaining what im talking about

1) h1 element class being added, no open quotation, no test runner is seen in preview pane
![image](https://user-images.githubusercontent.com/22984739/40274098-b50598f2-5b9c-11e8-81d3-9e5b2961ab3b.png)

2) h1 element class being added, open quotation and class name is present, test runner appears as soon as the single quotation " is typed in the editor

a) only the open quotation
![image](https://user-images.githubusercontent.com/22984739/40274149-a5a5e8de-5b9d-11e8-97f2-26a1035525b6.png)

b) open quotation with class name
![image](https://user-images.githubusercontent.com/22984739/40274137-5e514dc0-5b9d-11e8-8ba5-556a9e3f4a3b.png)

3) the addition of the class name is completed, so the quotation marks have both the opening and the closing and now the test runner disappears from the preview pane
![image](https://user-images.githubusercontent.com/22984739/40274163-fc298224-5b9d-11e8-957e-50153430fb6f.png)

**Comment by johnkennedy9147** [comment]
@Bouncey @mstellaluna I can recreate this issue, on Win7 in both FF and Chrome.  It looks like it is rendering some javascript when there is an unclosed attribute. ending in some base64 encoded data.

![image](https://user-images.githubusercontent.com/26827682/40310887-1debb620-5d06-11e8-893c-7f42b1736bb2.png)

It only happens if the unclosed attribute is on the last element and not followed by another attribute for example the invalid attribute is ignored here:
![image](https://user-images.githubusercontent.com/26827682/40312194-07900ac6-5d0a-11e8-9858-5107ad9fc9f0.png)

and here:
![image](https://user-images.githubusercontent.com/26827682/40312522-f92adf78-5d0a-11e8-8391-d329ec7faf59.png)


whereas here we get the rendered code:
![image](https://user-images.githubusercontent.com/26827682/40312286-5cd4b428-5d0a-11e8-92ed-150d02495a44.png)

Tried it with ID and style and similar behaviour seen.

Example text rendered (FYI the start seems to be clipped off):

```
e),checkChallengePayload=document.__checkChallengePayload;
function isPromise(e){return e&&"function"!=typeof e.subscribe&&"function"==typeof e.then}
const DeepEqual=(e,t)=>JSON.stringify(e)===JSON.stringify(t);
var DeepFreeze=e=>(Object.freeze(e),Object.getOwnPropertyNames(e).forEach(function(t){!e.hasOwnProperty(t)||null===e[t]||"object"!=typeof e[t]&&"function"!=typeof e[t]||Object.isFrozen(e[t])||DeepFreeze(e[t])}),e);
document.Enzyme&&(window.Enzyme=document.Enzyme),document.__getJsOutput=function getJsOutput(){if(window.__err)return window.__err;
let output;try{output=eval(source)}catch(e){output=e.message+"\n"+e.stack,window.__err=e}return output},document.__runTests=function runTests(tests=[]){const code=source,editor={getValue:()=>source};
return window.__err?Rx.Observable.from(tests).map(e=>Object.assign({},e,{err:window.__err.message+"\n"+window.__err.stack,message:window.__err.message,stack:window.__err.stack})).toArray().do(()=>{window.__err=null}):Rx.Observable.from(tests,null,null,Rx.Scheduler.default).delay(200).flatMap(({text:text,testString:testString})=>{const assert=chai.assert,getUserInput=__getUserInput,newTest={text:text,testString:testString};
let test,__result;
try{test=eval(testString),"function"==typeof test&&(__result=test(getUserInput),isPromise(__result)&&(__result=Rx.Observable.fromPromise(__result))),__result&&"function"==typeof __result.subscribe||(__result=Rx.Observable.of(null))}catch(e){__result=Rx.Observable.throw(e)}return __result.timeout(testTimeout).map(()=>(newTest.pass=!0,newTest)).catch(e=>{let t=e.message||"";
const r=t.indexOf(": expected");
return-1!==r&&(t=t.slice(0,r)),t=t.replace(/(.*?)<\/code>/g,"$1"),newTest.err=e.message+"\n"+e.stack,newTest.stack=e.stack,newTest.message=t,Rx.Observable.of(newTest)})}).toArray()},frameReady.next({checkChallengePayload:checkChallengePayload})})}]);
 //# sourceMappingURL=data:application/json;
 charset=utf-8; 
base64,eyJ2ZXJzaW9uIjozLCJ....this goes on and on and on so I cut it short
```

Let me know if you want the full text, there are about 12780 characters in the base64 encoded data,but it might be clipped off at the end also.

**Comment by johnkennedy9147** [comment]
@Bouncey @mstellaluna forgot to mention its not specific to the mentioned challenge, it happens in all the challenges with a preview pane.

**Comment by alvinkl** [comment]
@Bouncey I think it's because of the hot reload. 
Maybe we can just display more readable error message if the iframe runner catches an error. (I haven't investigate about this yet)
I'll try to fix it.

**Comment by nikrb** [comment]
yes I think it's unbalanced quotes, haven't found the tests yet thought - doh!

Looks like if there are other issues, e.g. invalid css color name, the Preview style is
changed to display='none', which I assume is done in the tests, somewhere.

in templates/Challenges/utils/frame.js::writeTestDepsToDocument:
`tests.__getUserInput = fileName => toString(sources[fileName]);`
seems a good place to check to it doesn't seem to be called.
writeTestDepsToDocument is called from createTestFramer yet doesn't seem to be called itself which is really confusing - a short circuit from rxjs/flow perhaps?

looking for checkChallengePayload atm but not found anything.

@Bouncey can you give us any pointers?

**Comment by nikrb** [comment]
good find dude. Fix seems to work, though can't help thinking the Preview pane should be cleared for invalid code (though I couldn't find it :). e.g. if you put an invalid css color name in, the Preview pane clears, rather than leaving the last valid Preview up. See what the 'powers that be' think.

**Comment by nikrb** [comment]
ignore me, seems I picked on the one thing that made it look like Preview pane is cleared. In fact invalid color leads to black, so it isn't cleared at all, just looks like it - doh!

**Comment by nikrb** [comment]
seems source [here](https://github.com/freeCodeCamp/learn/blob/00497f3dcdde99f165ac086368260a378f1474e6/src/client/frame-runner.js#L7) is appended to user solution when unbalanced quotes are present and gets passed to Preview. 

`e),checkChallengePayload=document.__checkChallengePayload;function isPromise(e)`

**Comment by moT01** [comment]
I think this issue affects the javascript challenges as well...
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator
this challenge wants `var myStr = "This is the start. " + "This is the end.";` as a solution - but if you remove the last quote - the test button does nothing

**Comment by nikrb** [comment]
Looks like the body is built [here](https://github.com/freeCodeCamp/learn/blob/1dca9b8e7ef25ace02cece080f4cda713b644a86/src/templates/Challenges/rechallenge/builders.js#L79).
It seems only double quotes cause the bleed over to Preview pane, as the contents are built by string concatenation.
We could put a check for matched quotes in here, but Preview pane will look ugly if we leave out the body, or append a quote.
:thinking: 
We could keep a last version of the body in the editor onChange handler, and display that instead?

**Comment by nikrb** [comment]
another possibility would be to throw an error on unbalanced quotes preventing the Preview pane update, similar to the babel transformer, "collapsing the pipeline" to quote bouncey's comment.
I have a patch ready but will wait to see how ValeraS's pr progresses.

**Comment by tchaffee** [comment]
@nikrb Which PR is that?

@Bouncey can we remove the "help wanted" label? Looks like @nikrb has a patch ready and someone else is working on a PR?

**Comment by nikrb** [comment]
@tchaffee not sure to which pr you refer. 
ValeraS pr is linked just above my comment.
I haven't created a pr, just putting forward ideas, quincy commented on another [pr](https://github.com/freeCodeCamp/learn/pull/87) that we should discuss the fix in this issue to find the best solution.
