### ISSUE TITLE
CTRL + Enter doesn't work to complete challenges (RWD)

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#67]
Challenge Name
All Projects under Responsive Web Design
(i.e) https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

Issue Description:
CTRL + Enter is not working to mark the project as completed. The button is working as normal.
There is no error in the console when using the CTRL + Enter to mark project complete.

**Comment by Bouncey** [comment]
I think it is triggering the form submit when you are pressing Enter, the Ctrl modifier isn't doing anything.

There is no user integration at this very minute, so nothing we seem completed in the map

**Comment by joops75** [comment]
I've fixed the issue of the Ctrl key having no effect when pressing enter on my machine (Windows 7 64-bit, Firefox Quantum 60.0.1 64-bit). It involves adding in 'onkeydown' and 'onkeyup' event listeners. Not sure if this approach is overkill. Should I submit a pull request? Alternatively, the button text could be simply changed from "I've completed this challenge (Ctrl + Enter)" to "I've completed this challenge (Enter)"

**Comment by tchaffee** [comment]
@Bouncey @joops75 Any update on this?

**Comment by Bouncey** [comment]
I don't think changing the hot keys between challenges is a good idea in terms of UX. 

As we are working with a form, we could add an `onKeyDown` prop to listen for `Ctrl || Cmd + Enter` which then calls `this.handleSubmit` ( this is from the top of my head, implementation would be different )

**Comment by joops75** [comment]
@Bouncey I've submitted a PR for this.

**Comment by Bouncey** [comment]
Closed via #181
