### ISSUE TITLE
Various Style and wording issues with learn

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/learn#75]
While QA'ing another PR I noticed several minor style and wording issues.

1. ![bootstrap___freecodecamp](https://user-images.githubusercontent.com/985197/40273919-9405d73c-5b8f-11e8-9c9a-641c227ca077.png)
2. ![welcome_to_learn_freecodecamp_](https://user-images.githubusercontent.com/985197/40274238-a26777ec-5b97-11e8-9d90-4ee8bfbd460e.png)
3. ![bootstrap___freecodecamp](https://user-images.githubusercontent.com/985197/40274242-abed4526-5b97-11e8-9b43-c6ce061e71bc.png)

**Comment by ekaoddlass** [comment]
![screen_shot_2018-05-21_at_12_26_01_am](https://user-images.githubusercontent.com/6597211/40281826-319c165e-5c90-11e8-8afb-c9addcd1ea32.png)

Re: point 2, then should we change the title here into (eg) "Curriculum"?

**Comment by mstellaluna** [comment]
i'm adding this also here instead of a separate one ... the View the curriculum button on the section intro pages is a different size and color than the go to the first lesson button

![image](https://user-images.githubusercontent.com/22984739/40285376-4c7b05e2-5c69-11e8-89e3-4a4eb7a80671.png)
