### ISSUE TITLE
jQuery code appears in the preview pane 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/learn#84]
Challenge Name(s)
jQuery - Target HTML Elements with Selectors Using jQuery 
https://learn.freecodecamp.org/front-end-libraries/jquery/target-html-elements-with-selectors-using-jquery
then each lesson in jQuery following this one .. 
it appears to be affecting the challenges as I can't pass any of them

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

Issue Description:
The jQuery code is appearing in the preview pane on the right hand side. This occurs as of the Target HTML Elements with Selectors Using jQuery. I have tested a majority of the lessons and the lessons don't pass. 

![image](https://user-images.githubusercontent.com/22984739/40309502-b742c0f4-5cd7-11e8-99e1-b48374b0bc4b.png)

![image](https://user-images.githubusercontent.com/22984739/40309810-dc1a03c8-5cd8-11e8-9fa5-a23ff6c38b33.png)

**Comment by Bouncey** [comment]
That's interesting... The script tags are being escaped, by us as well. I will dig into it.

Thanks @mstellaluna :sparkles: :sparkles:
