### ISSUE TITLE
"yarn develop" fails

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/learn#86]
`yarn develop` was working fine for me until today when I did a rebase over master. After the rebase, I ran `yarn install` which completed succesfully.

Now I'm getting this error when running `yarn develop`:

```
info bootstrap finished - 21.409 s

error Class constructor DefinePlugin cannot be invoked without 'new'


  TypeError: Class constructor DefinePlugin cannot be invoked without 'new'
  
  - plugin.js:8 new F
    [learn]/[webpack-configurator]/lib/resolve/plugin.js:8:33
  
  - plugin.js:13 
    [learn]/[webpack-configurator]/lib/resolve/plugin.js:13:16
  
  - plugin.js:14 module.exports
    [learn]/[webpack-configurator]/lib/resolve/plugin.js:14:8
  
  - index.js:180 Config.resolve
    [learn]/[webpack-configurator]/index.js:180:22
  
  - webpack-modify-validate.js:45 _callee$
    [learn]/[gatsby]/src/utils/webpack-modify-validate.js:45:43
  
  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7
  
  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
  

error Command failed with exit code 1.

```

# node --version
v8.11.1

# npm --version
5.6.0

# $(npm bin)/yarn --version
1.6.0

Ubuntu 16.04.4

**Comment by tchaffee** [comment]
@Bouncey why did you close this? Is this a dup or something?

**Comment by Bouncey** [comment]
Must have been a slip of the finger, sorry

**Comment by scissorsneedfoodtoo** [comment]
@tchaffee, are you still having a problem with this? I used nvm to switch to the same versions of node and npm you used and was able to complete the build. There were times in the past where I needed to run `yarn install` twice. Maybe that's causing the issue here?

**Comment by nikrb** [comment]
@tchaffee I can't reproduce this either. Have you tried `nvm install --lts` (courtesy raisedadead). Just a thought. I have:
node: 8.11.2
yarn: 1.6.0

**Comment by tchaffee** [comment]
I got it working now. Not sure what did the trick, but running `nvm install --lts` did **not** fix it. I deleted the `package.json.lock` and `yarn.lock` local files, did a rebase over upstream master, and now it's working. Thanks for your help!
