### ISSUE TITLE
Disable the minimap view on the monaco editor

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#90]
We do not want the minimap on the monaco editor.

**Comment by nikrb** [comment]
@raisedadead I've looked through a few sections (by no means all) but I don't see the minimap - unless I toggle the Editor options to true. Can you give us a link to where it is visible? (getting ready to blush here)

monaco options in templates/Challenges/classic/Editor.js Editor constructor:
```
    this.options = {
      minimap: {
        enabled: false
      },
      selectOnLineNumbers: true,
      wordWrap: 'on'
    };
```

**Comment by raisedadead** [comment]
Yup.. that's right. I must have been confused. Thanks a lot.
