### ISSUE TITLE
Increase the spacing in between the challenges

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#91]
![image](https://user-images.githubusercontent.com/1884376/40491065-becc902e-5f8a-11e8-9534-9498b0b40b99.png)

**Comment by nikrb** [comment]
@raisedadead contributing guidelines are a bit short, so thought I'd post here before pr'ing. The following seems to work, *if* 5px is enough space.
/templates/Introduction/intro.css:
```
.intro-toc .list-group-item {
  margin: 5px auto;
}
```

**Comment by raisedadead** [comment]
@nikrb works! Please proceed with a PR. And it would be awesome, if you can post a screenshot of how it looks when you have made the change.

**Comment by Bouncey** [comment]
Closed via #96
