### ISSUE TITLE
JSONP errors when new bundle available (ServiceWorker)

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/learn#93]
Well sorry for the bad background information on this one... 😅 

![bild](https://user-images.githubusercontent.com/6125097/40511987-b5e2d6aa-5fa1-11e8-9a66-a506baa6242c.png)

Unfortunately I don't have much information as I can't reproduce it.

This happened on the very first page load - all subsequent ones worked perfectly.

The Firefox v60.0.1 dev tools warned about 3 scripts that failed to load. 
When I clicked the button to open curricullum on the landing page, it threw an error instead of opening the modal.

The error said something about JSONP - but unfortunately I hit the refresh-button instead of screenshot-button...

Thanks for the work on the learn-update though. Keep it up! 🙂

**Comment by raisedadead** [comment]
That is fine, it could be a caching issue. And a refresh should actually fix it. I don't know if we have a clean way to let this be known to users.

**Comment by Greenheart** [comment]
Good point, the caching idea is potentially the problem - I had recently visited `learn.freecodecamp.org` from that browser.

In other browsers that loaded the new version, it worked fine.


I imagine a ServiceWorker, that could take control of the cache would be ideal to solve this without involving our users. It could work in the background to keep data offline as well as caching the main application bundle - and resolving issues like this one

**Comment by raisedadead** [comment]
We use, Gatsby there is a service worker there already.

**Comment by Greenheart** [comment]
Perhaps it could intercept the request for the new bundle version as well?
Or rather, if network is present, force-update to use the latest bundle.

**Comment by Bouncey** [comment]
There is a service worker, and it does require a refresh with the bundles update. I would welcome and improvement on this, or the removal is none is found.

**Comment by Greenheart** [comment]
![fcc-learn-cache-error](https://user-images.githubusercontent.com/6125097/40787838-de14b2a4-64ee-11e8-8d4a-6333b7a24ac0.png)
It happened again. Pretty sure this is a caching error, when the outdated service worker tries to fetch the old bundle that no longer exists.

And without any bundle to start the Learn-app, nothing happens once the button is clicked.

Since this occurred again now that I tried a new version than last time, I suspect this will happen if I try again once another update is released.

**To fix this,** could the service worker be updated to always request the latest bundle, rather than an outdated (seemingly hard coded) version that no longer exists on the server?

**Comment by Bouncey** [comment]
Service worker has been removed :+1:
