### ISSUE TITLE
/current-challenge on home does not have my current challenge.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#94]
@raisedadead commented on [Fri May 25 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17231)

![2018-05-25 02 12 15](https://user-images.githubusercontent.com/1884376/40512683-33dc0378-5fc1-11e8-83b7-0b29fb9fd351.gif)

---

@raisedadead commented on [Fri May 25 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17231#issuecomment-391853297)

I think my last challenge before this was at `HTML Uncomment Elements`

**Comment by Bouncey** [comment]
Your last challenge in the db is in the QA w/chai section, I don't think we are currently updating the current challenge from learn

**Comment by Bouncey** [comment]
On the action of `challengeMount`, we should update the users current challenge on the server. This requires a POST to `/external/update-my-current-challenge` with a body of `currentChallengeId`.

See the handler [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/bb4bcbfb45d8c3477aaba53101fb39e446c74a84/server/boot/settings.js#L56).

For this issue, you will require both learn and `freeCodeCamp/freeCodeCamp` running locally.

Happy coding!
